#!/bin/bash
rm -rf build
rm -rf dist
rm -rf venv
python3 -m venv venv
. venv/bin/activate
./venv/bin/pip install wheel twine
./venv/bin/python setup.py sdist bdist_wheel
twine upload dist/*
deactivate
