org: markolaban
app: realnet
service: realnet-api

provider:
  name: aws
  runtime: python3.7
  endpointType: REGIONAL

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true

custom:
  wsgi:
    app: realnet_wsgi_loader.wsgi.app
    pythonBin: python # Some systems with Python3 may require this
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  apigwBinary:
    types: #list of mime-types
      - 'image/*'
  slackDeployNotification:
     token: ${param:SLACK_ACCESS_TOKEN}
     channel:  ${param:SLACK_CHANNEL_ID}  

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-apigw-binary
  - "@schibsted/serverless-slack-deploy-notification"

package:
  exclude:
    - node_modules/**
    - venv/**
