# This is a basic workflow to help you get started with Actions

name:  Upload to PyPI

# Controls when the action will run. 
on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7 
      # bump version
      - name: "bump version -patch"
        run: |
          # install bump
          python3 -m pip install bump
          # bump version 
          bump
        # commit the change
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "bumped_version"
          commit_user_name: Nitharsan
          commit_user_email: nitharsan.puwanendran@l33tsystems.com
          commit_author: Nitharsan <nitharsan.puwanendran@l33tsystems.com> 

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine
          # If requirements.txt exists, install from it
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install the package from setup.py
          python3 setup.py install      
          
      # Upload to PyPI
      - name: Build and Upload to PyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}         